version: "2"
services:
  web:
    build: .
    command: puma
    ports:
      - 80:9292
    privileged: true
  agent:
    image: datadog/docker-dd-agent:latest
    ports:
      - 8125:8125/udp
    environment:
      - API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc
      - /cgroup/:/host/sys/fs/cgroup
    privileged: true
    labels:
      - convox.agent=true
